import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>AdminLTE 3 | Dashboard</title>

        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
        />

        <link
          rel="stylesheet"
          href="plugins/fontawesome-free/css/all.min.css"
        />

        <link
          rel="stylesheet"
          href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"
        />

        <link
          rel="stylesheet"
          href="plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css"
        />

        <link
          rel="stylesheet"
          href="plugins/icheck-bootstrap/icheck-bootstrap.min.css"
        />

        <link rel="stylesheet" href="plugins/jqvmap/jqvmap.min.css" />

        <link rel="stylesheet" href="dist/css/adminlte.min.css" />

        <link
          rel="stylesheet"
          href="plugins/overlayScrollbars/css/OverlayScrollbars.min.css"
        />

        <link
          rel="stylesheet"
          href="plugins/daterangepicker/daterangepicker.css"
        />

        <link
          rel="stylesheet"
          href="plugins/summernote/summernote-bs4.min.css"
        />
      </head>
      <body className="hold-transition sidebar-mini layout-fixed">
        {children}
      </body>
    </html>
  );
}
